### ISSUE TITLE
output files totally empty

### ISSUE THREAD

**Issue by JornPrengerFormeel** [richelbilderbeek/soto_project#1]
Look at the output.md, here you can see both output files are totally empty.

**Comment by JornPrengerFormeel** [comment]
it keeps saying "An error occurred. Could not demultiplex stream."

**Comment by JornPrengerFormeel** [comment]
I think it has something to do with the size of the video, because of the video.py file sets a frame size of 640 by 420 and the video is 1280 x 720. I set the video.py frame size to 1280 X 720 but its still giving the same error

**Comment by RafayelGardishyan** [comment]
Pull the new version and change your in your config setting "debug" : true -> "debug": false then it will work
